spring:
  application:
    name: centralize-sonar
server:
  port: 8181


sonar:
  url: "http://localhost:9000"
  token: "YOUR_SONARQ"
  username: "admin"
  password: "1234"
  metricKeys: "bugs,vulnerabilities,code_smells,coverage,duplicated_lines_density,security_hotspots,security_rating,reliability_rating"
